/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static test.FlightBuy.FlightPrice;

/**
 *
 * @author Ridho Syahfero
 */
public class HotelBuy extends javax.swing.JFrame {

    /**
     * Creates new form FlightBuy
     */
    public HotelBuy() throws ParseException {
        initComponents();
        String af = hotelFlight2.departureHot.getDate().toString();
        String parseAf = af.substring(0,10);
        String aff = hotelFlight2.returnDateHot.getDate().toString();
        String parseAff = aff.substring(0,10);
        jLabel13.setText(parseAf);
        jLabel14.setText(parseAff);
        jLabel10.setText(hotelFlight2.destinasi.getSelectedItem().toString());
        if(hotelFlight2.destinasi.getSelectedIndex() == 0){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/yellohoteljkt.png")));
            jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/milleniumjkt.png")));
            namaHoitel.setText("Millenium Hotel Sirih Jakarta");
            namaHoitel2.setText("YELLO Hotel Harmoni Jakarta");
            jLabel1.setText("Tanah Abang, Jakarta");
            jLabel2.setText("Gambir, Jakarta");
            hotelPrice.setText("RP 605.799");
            hotelPrice2.setText("RP 946.800");
        }else if(hotelFlight2.destinasi.getSelectedIndex() == 2){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/astonlombok.png")));
            jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/santikalombok.png")));
            namaHoitel.setText("Santika Hotel Lombok");
            namaHoitel2.setText("Aston Hotel Lombok");
            jLabel1.setText("Mataram, Lombok");
            jLabel2.setText("Mataram, Lombok");
            hotelPrice.setText("RP 349.210");
            hotelPrice2.setText("RP 689.000");
        }else if(hotelFlight2.destinasi.getSelectedIndex() == 3){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/harperbali.png")));
            jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/yellobali.png")));
            namaHoitel2.setText("Harper Hotel Bali");
            namaHoitel.setText("YELLO Hotel Bali");
            jLabel1.setText("Kuta, Bali");
            jLabel2.setText("Kuta, Bali");
            hotelPrice.setText("RP 645.865");
            hotelPrice2.setText("RP 968.125");
        }else if(hotelFlight2.destinasi.getSelectedIndex() == 4){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/astonnsurabaya.png")));
            jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grandsagamsurabaya.png")));namaHoitel.setText("Santika Hotel Lombok");
            namaHoitel2.setText("Aston Hotel Surabaya");
            namaHoitel.setText("Grand Sagam Hotel Surabaya");
            jLabel1.setText("Sidosermo, Surabaya");
            jLabel2.setText("Embong Kaliasin, Surabaya");
            hotelPrice.setText("RP 467.247");
            hotelPrice2.setText("RP 762.986");
        }else if(hotelFlight2.destinasi.getSelectedIndex() == 1){
            hotelPrice.setText("RP 532.932");
            hotelPrice2.setText("RP 769.890");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bayarHotel = new javax.swing.JButton();
        hotelPrice = new javax.swing.JLabel();
        namaHoitel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tes1 = new javax.swing.JCheckBox();
        tes2 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tes3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        bayarHotel2 = new javax.swing.JButton();
        hotelPrice2 = new javax.swing.JLabel();
        namaHoitel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotelbangka.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 15, 140, 130));

        bayarHotel.setBackground(new java.awt.Color(255, 102, 0));
        bayarHotel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bayarHotel.setForeground(new java.awt.Color(255, 255, 255));
        bayarHotel.setText("Pilih");
        bayarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarHotelActionPerformed(evt);
            }
        });
        jPanel2.add(bayarHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 137, -1));

        hotelPrice.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        hotelPrice.setForeground(new java.awt.Color(255, 102, 0));
        hotelPrice.setText("Rp 608.000");
        jPanel2.add(hotelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 52, 155, -1));

        namaHoitel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaHoitel.setText("Hotel Santika Bangka");
        jPanel2.add(namaHoitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 510, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star4.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Location_28px_1.png"))); // NOI18N
        jLabel2.setText("Taman Sari, Bangka");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 320, 30));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel41.setText("/Kamar");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 100, -1));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_left_80px_1.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1541, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Your Destination");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Departure Date :");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Return Date :");

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Worldwide_Location_26px.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Destination:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("jLabel13");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel49))
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(31, 31, 31))
        );

        tes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tes1ActionPerformed(evt);
            }
        });

        tes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tes2ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star4.png"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel40.setText("Hotels");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_5_Star_Hotel_28px.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star4.png"))); // NOI18N

        tes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tes3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("All Rated Star Hotel");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tes2)
                            .addComponent(tes1)
                            .addComponent(tes3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel50))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tes3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tes1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28)))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(tes2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/JelajahiDunia (1).png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotelbangka2.jpeg"))); // NOI18N
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 130));

        bayarHotel2.setBackground(new java.awt.Color(255, 102, 0));
        bayarHotel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bayarHotel2.setForeground(new java.awt.Color(255, 255, 255));
        bayarHotel2.setText("Pilih");
        bayarHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarHotel2ActionPerformed(evt);
            }
        });
        jPanel7.add(bayarHotel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 137, -1));

        hotelPrice2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        hotelPrice2.setForeground(new java.awt.Color(255, 102, 0));
        hotelPrice2.setText("Rp 680.000");
        jPanel7.add(hotelPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 52, 155, -1));

        namaHoitel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaHoitel2.setText("Swiss Bell Bangka");
        jPanel7.add(namaHoitel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 500, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/star4.png"))); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 116, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Location_28px_1.png"))); // NOI18N
        jLabel1.setText("Taman Sari, Bangka");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 340, 30));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel42.setText("/Kamar");
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 100, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tes2ActionPerformed
       jPanel2.setVisible(false);
       jPanel7.setVisible(true);
       tes1.setSelected(false);
       tes3.setSelected(false);
    }//GEN-LAST:event_tes2ActionPerformed

    private void tes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tes1ActionPerformed
        jPanel7.setVisible(false);
        jPanel2.setVisible(true);
        tes2.setSelected(false);
        tes3.setSelected(false);
    }//GEN-LAST:event_tes1ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void bayarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarHotelActionPerformed
        PaymentFrame pay = new PaymentFrame();
        pay.namaT.setText("Hotel Anda");
        pay.namaT2.setText("Wilayah Hotel");
        pay.iconG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_5_Star_Hotel_28px.png")));
        pay.dest1.setText(jLabel2.getText());
        pay.dest2.setVisible(false);
        pay.dest3.setText("Dewasa x" + hotelFlight2.dewasaHot.getValue());
        pay.dest4.setText("Anak x" + hotelFlight2.anakHot.getValue());
        pay.namapes1.setText(namaHoitel.getText());
        pay.hargaBayar.setText(hotelPrice.getText());
        pay.namapes8.setText(namaHoitel.getText());
        pay.hargaBayar1.setText(hotelPrice.getText());
        dispose();
        pay.setVisible(true);
    }//GEN-LAST:event_bayarHotelActionPerformed

    private void bayarHotel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarHotel2ActionPerformed
        PaymentFrame pay = new PaymentFrame();
        pay.namaT.setText("Hotel Anda");
        pay.namaT2.setText("Wilayah Hotel");
        pay.iconG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_5_Star_Hotel_28px.png")));
        pay.dest1.setText(jLabel1.getText());
        pay.dest2.setVisible(false);
        pay.dest3.setText("Dewasa x" + hotelFlight2.dewasaHot.getValue());
        pay.dest4.setText("Anak x" + hotelFlight2.anakHot.getValue());
        pay.namapes1.setText(namaHoitel2.getText());
        pay.hargaBayar.setText(hotelPrice2.getText());
        pay.namapes8.setText(namaHoitel2.getText());
        pay.hargaBayar1.setText(hotelPrice2.getText());
        dispose();
        pay.setVisible(true);
    }//GEN-LAST:event_bayarHotel2ActionPerformed

    private void tes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tes3ActionPerformed
        jPanel7.setVisible(true);
        jPanel2.setVisible(true);
        tes2.setSelected(false);
        tes1.setSelected(false);
    }//GEN-LAST:event_tes3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatIntelliJLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HotelBuy().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(HotelBuy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bayarHotel;
    public static javax.swing.JButton bayarHotel2;
    public static javax.swing.JLabel hotelPrice;
    public static javax.swing.JLabel hotelPrice2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JLabel namaHoitel;
    public static javax.swing.JLabel namaHoitel2;
    public static javax.swing.JCheckBox tes1;
    public static javax.swing.JCheckBox tes2;
    public static javax.swing.JCheckBox tes3;
    // End of variables declaration//GEN-END:variables
}
