/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import Connection.DatabaseConnection;
import java.sql.*;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author DELL
 */
public class hotelFlight2 extends javax.swing.JFrame {
    String datepa, dateNow;
    private final Connection con;
    /**
     * Creates new form TransparentFrame
     */
    public hotelFlight2() {
        initComponents();
        con = DatabaseConnection.getInstance().getCon();
        dewasaHot.setValue(1);
        Dewasa.setValue(1);
        LocalDateTime now = LocalDateTime.now();
        String sDate = now.toString();
        Date date1;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(sDate);
            dateNow = date1.toString().substring(4,7);
            datepa = date1.toString().substring(8,10);
            departuree.setDate(date1);
            departureHot.setDate(date1);
            
        } catch (ParseException ex) {
            Logger.getLogger(hotelFlight2.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
        this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
       jPanel1.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
       materialTabbed2.setVisible(false);
       ((SpinnerNumberModel) dewasaHot.getModel()).setMinimum(0);
       ((SpinnerNumberModel) anakHot.getModel()).setMinimum(0);
       ((SpinnerNumberModel) Dewasa.getModel()).setMinimum(0);
       ((SpinnerNumberModel) totalAnak.getModel()).setMinimum(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageSlider1 = new test.ImageSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        materialTabbed1 = new swing.MaterialTabbed();
        flightTicket = new javax.swing.JPanel();
        departuree = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        returnDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalAnak = new javax.swing.JSpinner();
        Dewasa = new javax.swing.JSpinner();
        seatClasss = new swing.Combobox();
        fromm = new swing.Combobox();
        too = new swing.Combobox();
        jLabel24 = new javax.swing.JLabel();
        button11 = new swing.Button();
        jLabel9 = new javax.swing.JLabel();
        materialTabbed2 = new swing.MaterialTabbed();
        hotelTickett = new javax.swing.JPanel();
        returnDateHot = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        anakHot = new javax.swing.JSpinner();
        dewasaHot = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        button8 = new swing.Button();
        destinasi = new swing.Combobox();
        jLabel17 = new javax.swing.JLabel();
        departureHot = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1100));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel1.setText("Discover More >");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel2.setText("EXPLORE INDONESIA");

        materialTabbed1.setForeground(new java.awt.Color(255, 255, 255));
        materialTabbed1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        materialTabbed1.setPreferredSize(new java.awt.Dimension(735, 287));
        materialTabbed1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                materialTabbed1StateChanged(evt);
            }
        });
        materialTabbed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialTabbed1MouseClicked(evt);
            }
        });

        flightTicket.setBackground(new java.awt.Color(255, 255, 255));
        flightTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        flightTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        flightTicket.setLayout(null);

        departuree.setBackground(new java.awt.Color(255, 255, 255));
        departuree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(departuree);
        departuree.setBounds(41, 120, 200, 33);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Departure Date");
        flightTicket.add(jLabel3);
        jLabel3.setBounds(41, 91, 116, 23);

        returnDate.setBackground(new java.awt.Color(255, 255, 255));
        returnDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(returnDate);
        returnDate.setBounds(276, 120, 210, 33);

        jLabel4.setBackground(new java.awt.Color(51, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Seat Class");
        flightTicket.add(jLabel4);
        jLabel4.setBounds(510, 90, 116, 23);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("To");
        flightTicket.add(jLabel5);
        jLabel5.setBounds(275, 20, 116, 23);

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Child");
        flightTicket.add(jLabel6);
        jLabel6.setBounds(280, 170, 116, 23);

        jLabel7.setBackground(new java.awt.Color(51, 204, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("From");
        flightTicket.add(jLabel7);
        jLabel7.setBounds(41, 20, 116, 23);

        jLabel8.setBackground(new java.awt.Color(51, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Adult");
        flightTicket.add(jLabel8);
        jLabel8.setBounds(40, 170, 116, 23);
        flightTicket.add(totalAnak);
        totalAnak.setBounds(280, 206, 210, 30);
        flightTicket.add(Dewasa);
        Dewasa.setBounds(40, 206, 200, 30);

        seatClasss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seatClasss.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "Business", "First" }));
        seatClasss.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatClasss.setLabeText("");
        seatClasss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatClasssActionPerformed(evt);
            }
        });
        flightTicket.add(seatClasss);
        seatClasss.setBounds(510, 120, 208, 34);

        fromm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fromm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        fromm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromm.setLabeText("");
        fromm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frommActionPerformed(evt);
            }
        });
        flightTicket.add(fromm);
        fromm.setBounds(40, 50, 200, 34);

        too.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        too.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)" }));
        too.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        too.setLabeText("");
        too.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tooActionPerformed(evt);
            }
        });
        flightTicket.add(too);
        too.setBounds(270, 50, 200, 34);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(45, 45));
        flightTicket.add(jLabel24);
        jLabel24.setBounds(530, 200, 40, 40);

        button11.setBackground(new java.awt.Color(0, 153, 255));
        button11.setForeground(new java.awt.Color(255, 255, 255));
        button11.setText("SEARCH FLIGHTS");
        button11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        flightTicket.add(button11);
        button11.setBounds(520, 200, 190, 39);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Return Date");
        flightTicket.add(jLabel9);
        jLabel9.setBounds(280, 90, 90, 20);

        materialTabbed1.addTab("FLIGHTS", flightTicket);

        materialTabbed2.setForeground(new java.awt.Color(255, 255, 255));
        materialTabbed2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        materialTabbed2.setPreferredSize(new java.awt.Dimension(735, 287));
        materialTabbed2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                materialTabbed2StateChanged(evt);
            }
        });
        materialTabbed2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialTabbed2MouseClicked(evt);
            }
        });

        hotelTickett.setBackground(new java.awt.Color(255, 255, 255));
        hotelTickett.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        hotelTickett.setPreferredSize(new java.awt.Dimension(800, 400));
        hotelTickett.setLayout(null);

        returnDateHot.setBackground(new java.awt.Color(255, 255, 255));
        returnDateHot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTickett.add(returnDateHot);
        returnDateHot.setBounds(280, 120, 200, 33);

        jLabel15.setBackground(new java.awt.Color(51, 204, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Check-in :");
        hotelTickett.add(jLabel15);
        jLabel15.setBounds(41, 91, 116, 23);

        jLabel18.setBackground(new java.awt.Color(51, 204, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Child");
        hotelTickett.add(jLabel18);
        jLabel18.setBounds(280, 170, 116, 23);

        jLabel19.setBackground(new java.awt.Color(51, 204, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Destiination or City");
        hotelTickett.add(jLabel19);
        jLabel19.setBounds(41, 20, 116, 23);

        jLabel20.setBackground(new java.awt.Color(51, 204, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Adult");
        hotelTickett.add(jLabel20);
        jLabel20.setBounds(40, 170, 116, 23);
        hotelTickett.add(anakHot);
        anakHot.setBounds(280, 206, 210, 30);
        hotelTickett.add(dewasaHot);
        dewasaHot.setBounds(40, 206, 200, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(45, 45));
        hotelTickett.add(jLabel21);
        jLabel21.setBounds(530, 200, 40, 40);

        button8.setBackground(new java.awt.Color(0, 153, 255));
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setText("SEARCH HOTEL");
        button8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        hotelTickett.add(button8);
        button8.setBounds(530, 200, 190, 39);

        destinasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        destinasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)", "Surabaya (SBY)" }));
        destinasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        destinasi.setLabeText("");
        destinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinasiActionPerformed(evt);
            }
        });
        hotelTickett.add(destinasi);
        destinasi.setBounds(40, 50, 200, 34);

        jLabel17.setBackground(new java.awt.Color(51, 204, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Check-out :");
        hotelTickett.add(jLabel17);
        jLabel17.setBounds(280, 90, 116, 23);

        departureHot.setBackground(new java.awt.Color(255, 255, 255));
        departureHot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTickett.add(departureHot);
        departureHot.setBounds(41, 120, 200, 33);

        materialTabbed2.addTab("HOTELS", hotelTickett);

        jLayeredPane2.setLayer(materialTabbed1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(materialTabbed2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(materialTabbed2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materialTabbed2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void materialTabbed1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTabbed1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_materialTabbed1MouseClicked

    private void materialTabbed1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_materialTabbed1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_materialTabbed1StateChanged

    private void materialTabbed2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTabbed2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_materialTabbed2MouseClicked

    private void materialTabbed2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_materialTabbed2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_materialTabbed2StateChanged

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
String a = departuree.getDate().toString();
String cd = a.substring(24);
String pattern = "yyyy-MM-dd";
SimpleDateFormat fm = new SimpleDateFormat(pattern);
String depaFm =fm.format(departuree.getDate());
String retFm = fm.format(returnDate.getDate());
String b = a.substring(8,10);
String date2 = a.substring(4,7);
int tes1 = Integer.parseInt(b);
//if(returnDate.getDate() == null){
//        if(tes1 >= Integer.parseInt(datepa) && cd.equals("2023") && date2.equalsIgnoreCase(dateNow) && tes1 >= 25){
//            dispose();
//        FlightBuy flight = null;
//        try {
//            String query = "INSERT INTO flight (from_destination,to_destination,departure_date,return_date,passenger_adults,passengger_childs,seat_class) VALUES(?,?,?,?,?,?,?)";
//            DatabaseConnection.pst = con.prepareStatement(query);
//            DatabaseConnection.pst.setString(1, ""+fromm.getSelectedItem());
//            DatabaseConnection.pst.setString(2, ""+too.getSelectedItem());
//            DatabaseConnection.pst.setString(3, depaFm);
//            if(returnDate.getDate() == null){
//            DatabaseConnection.pst.setString(4, retFm);
//                
//            }
//            DatabaseConnection.pst.setString(5, ""+Dewasa.getValue());
//            DatabaseConnection.pst.setString(6, ""+totalAnak.getValue());
//            DatabaseConnection.pst.setString(7, ""+seatClasss.getSelectedItem());
//            DatabaseConnection.pst.execute();
//        
//            flight = new FlightBuy();
//            flight.setVisible(true);
//        } catch (ParseException | SQLException ex) {
//            ex.printStackTrace();
//        }
//    }else{
//        JOptionPane.showMessageDialog(null, "Tolong Masukan Form Pemberangkatan Dengan Tahun Dan Bulan Saat Ini");         
//    }
//}else{
    String c = returnDate.getDate().toString();
    String d = c.substring(8,10);
    String dc = c.substring(24);
    String date = c.substring(4,7);
    int tes = Integer.parseInt(d);
        if(tes1 >= Integer.parseInt(datepa) && dc.equals("2023") && cd.equals("2023") && date.equalsIgnoreCase(dateNow) && date2.equalsIgnoreCase(dateNow) && tes >= tes1){
            FlightBuy flight;
        try {
            String query = "INSERT INTO flight (from_destination,to_destination,departure_date,return_date,passenger_adults,passengger_childs,seat_class) VALUES(?,?,?,?,?,?,?)";
            DatabaseConnection.pst = con.prepareStatement(query);
            DatabaseConnection.pst.setString(1, ""+fromm.getSelectedItem());
            DatabaseConnection.pst.setString(2, ""+too.getSelectedItem());
            DatabaseConnection.pst.setString(3, depaFm);
            DatabaseConnection.pst.setString(4, retFm);
            DatabaseConnection.pst.setString(5, ""+Dewasa.getValue());
            DatabaseConnection.pst.setString(6, ""+totalAnak.getValue());
            DatabaseConnection.pst.setString(7, ""+seatClasss.getSelectedItem());
            DatabaseConnection.pst.execute();
        
            flight = new FlightBuy();
            flight.setVisible(true);
        } catch (ParseException | SQLException ex) {
             ex.printStackTrace();
        }
        }else{
            JOptionPane.showMessageDialog(null, "Tolong Masukan Form Pemberangkatan Dengan Tahun Dan Bulan Saat Ini");         
        }
//    }
    }//GEN-LAST:event_button11ActionPerformed

    private void tooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tooActionPerformed

    private void frommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frommActionPerformed

    private void seatClasssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatClasssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatClasssActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
    String a = departureHot.getDate().toString();
    String cd = a.substring(24);
    String b = a.substring(8,10);
    String date2 = a.substring(4,7);
    String pattern = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(pattern);
    String depaFm =fm.format(departureHot.getDate());
    String retFm = fm.format(returnDateHot.getDate());
    int tes1 = Integer.parseInt(b);
        if(returnDateHot.getDate() == null){
            JOptionPane.showMessageDialog(null, "Harap memasukan form return date");         
        }else{
            String c = returnDateHot.getDate().toString();
            String d = c.substring(8,10);
            String dc = c.substring(24);
            String date = c.substring(4,7);
            int tes = Integer.parseInt(d);
                if(tes1 >= Integer.parseInt(datepa) && dc.equals("2023") && cd.equals("2023") && date.equalsIgnoreCase(dateNow) && date2.equalsIgnoreCase(dateNow) && tes > tes1){
                    dispose();
                    HotelBuy hotel;
                try {
                    String query = "INSERT INTO hotel (destinasi,checkin,checkout,guest_adult,guest_child) VALUES(?,?,?,?,?)";
                    DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, ""+destinasi.getSelectedItem());
                    DatabaseConnection.pst.setString(2, depaFm);
                    DatabaseConnection.pst.setString(3, retFm);
                    DatabaseConnection.pst.setString(4, ""+dewasaHot.getValue());
                    DatabaseConnection.pst.setString(5, ""+anakHot.getValue());
                    DatabaseConnection.pst.execute();
        
                    hotel = new HotelBuy();
                    hotel.setVisible(true);
                } catch (ParseException | SQLException ex) {
                   ex.printStackTrace();
                }
                }else{
                    JOptionPane.showMessageDialog(null, "Tolong Masukan Form Pemberangkatan Dengan Tahun Dan Bulan Saat Ini");         
                }
            }
    }//GEN-LAST:event_button8ActionPerformed

    private void destinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelFlight2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelFlight2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelFlight2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelFlight2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            DatabaseConnection.getInstance().connectToDatabase();
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelFlight2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner Dewasa;
    public static javax.swing.JSpinner anakHot;
    private swing.Button button11;
    private swing.Button button8;
    public static com.toedter.calendar.JDateChooser departureHot;
    public static com.toedter.calendar.JDateChooser departuree;
    public static swing.Combobox destinasi;
    public static javax.swing.JSpinner dewasaHot;
    private javax.swing.JPanel flightTicket;
    public static swing.Combobox fromm;
    public static javax.swing.JPanel hotelTickett;
    private test.ImageSlider imageSlider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JPanel jPanel1;
    public static swing.MaterialTabbed materialTabbed1;
    public static swing.MaterialTabbed materialTabbed2;
    private com.toedter.calendar.JDateChooser returnDate;
    public static com.toedter.calendar.JDateChooser returnDateHot;
    public static swing.Combobox seatClasss;
    public static swing.Combobox too;
    public static javax.swing.JSpinner totalAnak;
    // End of variables declaration//GEN-END:variables
}
