/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;

/**
 *
 * @author DELL
 */
public class hotelFlight extends javax.swing.JFrame {

    /**
     * Creates new form TransparentFrame
     */
    public hotelFlight() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
       jPanel1.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
       hotelTicket.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageSlider1 = new test.ImageSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        flightButton = new swing.Button();
        hotelButton = new swing.Button();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        flightTicket = new javax.swing.JPanel();
        departure = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        returnDate = new com.toedter.calendar.JDateChooser();
        button4 = new swing.Button();
        to = new swing.Combobox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        seatClass = new swing.Combobox();
        from = new swing.Combobox();
        hotelTicket = new javax.swing.JPanel();
        departure2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        from2 = new swing.Combobox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        departure4 = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        button5 = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1100));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel1.setText("Discover More >");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel2.setText("EXPLORE INDONESIA");

        flightButton.setBackground(new java.awt.Color(0, 153, 255));
        flightButton.setForeground(new java.awt.Color(255, 255, 255));
        flightButton.setText("FLIGHTS");
        flightButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightButtonActionPerformed(evt);
            }
        });

        hotelButton.setBackground(new java.awt.Color(0, 153, 255));
        hotelButton.setForeground(new java.awt.Color(255, 255, 255));
        hotelButton.setText("HOTELS");
        hotelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelButtonActionPerformed(evt);
            }
        });

        flightTicket.setBackground(new java.awt.Color(255, 255, 255));
        flightTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        flightTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        flightTicket.setLayout(null);

        departure.setBackground(new java.awt.Color(255, 255, 255));
        departure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(departure);
        departure.setBounds(41, 120, 200, 33);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Departure Date");
        flightTicket.add(jLabel3);
        jLabel3.setBounds(41, 91, 116, 23);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Return Date");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        flightTicket.add(jRadioButton1);
        jRadioButton1.setBounds(275, 92, 100, 21);

        returnDate.setBackground(new java.awt.Color(255, 255, 255));
        returnDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(returnDate);
        returnDate.setBounds(276, 120, 210, 33);

        button4.setBackground(new java.awt.Color(0, 153, 255));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("SEARCH FLIGHTS");
        button4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        flightTicket.add(button4);
        button4.setBounds(520, 200, 164, 39);

        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)" }));
        to.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        to.setLabeText("");
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        flightTicket.add(to);
        to.setBounds(270, 50, 220, 34);

        jLabel4.setBackground(new java.awt.Color(51, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seat Class");
        flightTicket.add(jLabel4);
        jLabel4.setBounds(510, 90, 116, 23);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("To");
        flightTicket.add(jLabel5);
        jLabel5.setBounds(275, 20, 116, 23);

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Child");
        flightTicket.add(jLabel6);
        jLabel6.setBounds(280, 170, 116, 23);

        jLabel7.setBackground(new java.awt.Color(51, 204, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("From");
        flightTicket.add(jLabel7);
        jLabel7.setBounds(41, 20, 116, 23);

        jLabel8.setBackground(new java.awt.Color(51, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Adult");
        flightTicket.add(jLabel8);
        jLabel8.setBounds(40, 170, 116, 23);
        flightTicket.add(jSpinner1);
        jSpinner1.setBounds(280, 206, 210, 30);
        flightTicket.add(jSpinner2);
        jSpinner2.setBounds(40, 206, 200, 30);

        seatClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seatClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "Business", "First" }));
        seatClass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatClass.setLabeText("");
        seatClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatClassActionPerformed(evt);
            }
        });
        flightTicket.add(seatClass);
        seatClass.setBounds(510, 120, 208, 34);

        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        from.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from.setLabeText("");
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        flightTicket.add(from);
        from.setBounds(40, 50, 200, 34);

        hotelTicket.setBackground(new java.awt.Color(255, 255, 255));
        hotelTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        hotelTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        hotelTicket.setLayout(null);

        departure2.setBackground(new java.awt.Color(255, 255, 255));
        departure2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTicket.add(departure2);
        departure2.setBounds(270, 160, 180, 33);

        jLabel25.setBackground(new java.awt.Color(51, 204, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Check Out");
        hotelTicket.add(jLabel25);
        jLabel25.setBounds(270, 130, 116, 23);

        from2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)", "Bangka (PGK)", "Lombok (LOP)" }));
        from2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from2.setLabeText("");
        from2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from2ActionPerformed(evt);
            }
        });
        hotelTicket.add(from2);
        from2.setBounds(30, 80, 590, 34);

        jLabel31.setBackground(new java.awt.Color(51, 204, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Destination or City");
        hotelTicket.add(jLabel31);
        jLabel31.setBounds(30, 50, 116, 23);

        jLabel32.setBackground(new java.awt.Color(51, 204, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Hotel Details");
        hotelTicket.add(jLabel32);
        jLabel32.setBounds(30, 20, 116, 23);

        departure4.setBackground(new java.awt.Color(255, 255, 255));
        departure4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTicket.add(departure4);
        departure4.setBounds(30, 160, 200, 33);

        jLabel36.setBackground(new java.awt.Color(51, 204, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Check In");
        hotelTicket.add(jLabel36);
        jLabel36.setBounds(30, 130, 116, 23);

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Guests");
        hotelTicket.add(jLabel37);
        jLabel37.setBounds(470, 130, 40, 23);
        hotelTicket.add(jSpinner7);
        jSpinner7.setBounds(470, 160, 100, 30);

        jLabel38.setBackground(new java.awt.Color(51, 204, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Rooms");
        hotelTicket.add(jLabel38);
        jLabel38.setBounds(590, 130, 40, 23);
        hotelTicket.add(jSpinner8);
        jSpinner8.setBounds(590, 160, 90, 30);

        jLabel28.setBackground(new java.awt.Color(51, 204, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Child");
        hotelTicket.add(jLabel28);
        jLabel28.setBounds(270, 210, 116, 23);

        jLabel30.setBackground(new java.awt.Color(51, 204, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Adult");
        hotelTicket.add(jLabel30);
        jLabel30.setBounds(30, 210, 116, 23);
        hotelTicket.add(jSpinner5);
        jSpinner5.setBounds(270, 230, 210, 30);
        hotelTicket.add(jSpinner6);
        jSpinner6.setBounds(30, 230, 200, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(45, 45));
        hotelTicket.add(jLabel17);
        jLabel17.setBounds(520, 220, 40, 40);

        button5.setBackground(new java.awt.Color(0, 153, 255));
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setText("SEARCH HOTELS");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        hotelTicket.add(button5);
        button5.setBounds(514, 220, 190, 39);

        jLayeredPane2.setLayer(flightTicket, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(hotelTicket, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hotelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hotelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(306, 306, 306))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(flightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void flightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightButtonActionPerformed
        // TODO add your handling code here:
        flightTicket.setVisible(true);
        hotelTicket.setVisible(false);
    }//GEN-LAST:event_flightButtonActionPerformed

    private void hotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelButtonActionPerformed
        // TODO add your handling code here:
        flightTicket.setVisible(false);
        hotelTicket.setVisible(true);
    }//GEN-LAST:event_hotelButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            returnDate.setVisible(true);
        }else{
            returnDate.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void seatClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatClassActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void from2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button4;
    private swing.Button button5;
    private com.toedter.calendar.JDateChooser departure;
    private com.toedter.calendar.JDateChooser departure2;
    private com.toedter.calendar.JDateChooser departure4;
    private swing.Button flightButton;
    private javax.swing.JPanel flightTicket;
    private swing.Combobox from;
    private swing.Combobox from2;
    private swing.Button hotelButton;
    private javax.swing.JPanel hotelTicket;
    private test.ImageSlider imageSlider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private com.toedter.calendar.JDateChooser returnDate;
    private swing.Combobox seatClass;
    private swing.Combobox to;
    // End of variables declaration//GEN-END:variables
}
