/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import switchbutton.SwitchListener;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import swing.GradientDropdownMenu;
import swing.MenuEvent;


/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        slideshow1.initSlideshow(new Slide1(), new Slide2(), new Slide3(), new Slide4());
//        contentPane.se
        switchOnOff.addEventSwitchSelected(new SwitchListener() {
            @Override
            public void selectChange(boolean on) {
               if(on == true){
                    EventQueue.invokeLater(() -> {
                    FlatAnimatedLafChange.showSnapshot();
                    FlatDarculaLaf.setup();
                    FlatLaf.updateUI();
                    FlatAnimatedLafChange.hideSnapshotWithAnimation();
                    mainPage.setBackground(Color.DARK_GRAY);
                    switchOnOff.setSwitchColor(new Color(102,204,255));
                    switchOnOff.setForeground(Color.BLACK);
                    transportation homeTab = new transportation();
                    homeTab.mainPage.setBackground(Color.DARK_GRAY);
                    });
               }else{
                    EventQueue.invokeLater(() -> {
                    FlatAnimatedLafChange.showSnapshot();
                    FlatIntelliJLaf.setup();
                    FlatLaf.updateUI();
                    FlatAnimatedLafChange.hideSnapshotWithAnimation();
                    mainPage.setBackground(Color.WHITE);
                    transportation homeTab = new transportation();
                    homeTab.mainPage.setBackground(Color.WHITE);
                    switchOnOff.setSwitchColor(new Color(102,204,255));
                    switchOnOff.setForeground(Color.BLACK);   
                    });
               }
            }
        });
        GradientDropdownMenu menu = new GradientDropdownMenu();
        menu.addItem("Home");
        menu.addItem("Transport", "Flights", "Flight And Hotel");
        
        menu.addItem("Accomodations", "Hotels", "Flight And Hotel");
        menu.setFont(new java.awt.Font("sansserif", 1, 14));
        menu.applay(this);
        menu.addEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex, boolean menuItem) {
                    hotelFlight low = new hotelFlight();
                    Main ui = new Main();
                    hotelFlight2 page2 = new hotelFlight2();
                    transportation trans = new transportation();
                if (menu.getMenuNameAt(index, subIndex).trim().equals("Flights") || menu.getMenuNameAt(index, subIndex).trim().equals("Flight And Hotel")) {
                   showForm(page2.jPanel1);
                   hotelFlight2.materialTabbed1.setVisible(true);
                   hotelFlight2.materialTabbed2.setVisible(false);
                }else if (menu.getMenuNameAt(index, subIndex).trim().equals("Home")) {
                    showForm(ui.mainPage);
                }else if (menu.getMenuNameAt(index, subIndex).trim().equals("Hotels") || menu.getMenuNameAt(index, subIndex).trim().equals("Flight And Hotel")) {
                   showForm(page2.jPanel1);
                   hotelFlight2.materialTabbed1.setVisible(false);
                   hotelFlight2.materialTabbed2.setVisible(true);
                }
            }
        });
         seatClass.setForeground(Color.black);
        country.setForeground(Color.black);
        from.setForeground(Color.black);
        to.setForeground(Color.black);
        returnDate.setVisible(false);
        mainPage.setVisible(true);
        hotelTicket.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPage = new javax.swing.JPanel();
        switchOnOff = new switchbutton.SwitchButton();
        jLabel2 = new javax.swing.JLabel();
        flightButton = new swing.Button();
        hotelButton = new swing.Button();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slideshow1 = new slideshow.Slideshow();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        flightTicket = new javax.swing.JPanel();
        departure = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        returnDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        seatClass = new swing.Combobox();
        from = new swing.Combobox();
        to = new swing.Combobox();
        jLabel18 = new javax.swing.JLabel();
        button6 = new swing.Button();
        hotelTicket = new javax.swing.JPanel();
        departure2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        from2 = new swing.Combobox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        departure4 = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        button5 = new swing.Button();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        flightButton1 = new swing.Button();
        country = new swing.Combobox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 1100));
        getContentPane().setLayout(null);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1600, 1100));

        mainPage.setBackground(new java.awt.Color(255, 255, 255));
        mainPage.setPreferredSize(new java.awt.Dimension(1550, 915));

        switchOnOff.setForeground(new java.awt.Color(0, 0, 0));
        switchOnOff.setOn(false);
        switchOnOff.setRound(999);
        switchOnOff.setSwitchColor(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Dark Mode");

        flightButton.setBackground(new java.awt.Color(0, 153, 255));
        flightButton.setForeground(new java.awt.Color(255, 255, 255));
        flightButton.setText("FLIGHTS");
        flightButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightButtonActionPerformed(evt);
            }
        });

        hotelButton.setBackground(new java.awt.Color(0, 153, 255));
        hotelButton.setForeground(new java.awt.Color(255, 255, 255));
        hotelButton.setText("HOTELS");
        hotelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelButtonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image12.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(310, 150));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        slideshow1.setForeground(new java.awt.Color(102, 255, 255));
        slideshow1.setPreferredSize(new java.awt.Dimension(478, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image6.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        flightTicket.setBackground(new java.awt.Color(255, 255, 255));
        flightTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        flightTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        flightTicket.setLayout(null);

        departure.setBackground(new java.awt.Color(255, 255, 255));
        departure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(departure);
        departure.setBounds(41, 120, 200, 33);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Departure Date");
        flightTicket.add(jLabel3);
        jLabel3.setBounds(41, 91, 116, 23);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Return Date");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        flightTicket.add(jRadioButton1);
        jRadioButton1.setBounds(275, 92, 100, 21);

        returnDate.setBackground(new java.awt.Color(255, 255, 255));
        returnDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(returnDate);
        returnDate.setBounds(276, 120, 210, 33);

        jLabel4.setBackground(new java.awt.Color(51, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seat Class");
        flightTicket.add(jLabel4);
        jLabel4.setBounds(510, 90, 116, 23);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("To");
        flightTicket.add(jLabel5);
        jLabel5.setBounds(275, 20, 116, 23);

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Child");
        flightTicket.add(jLabel6);
        jLabel6.setBounds(280, 170, 116, 23);

        jLabel7.setBackground(new java.awt.Color(51, 204, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("From");
        flightTicket.add(jLabel7);
        jLabel7.setBounds(41, 20, 116, 23);

        jLabel8.setBackground(new java.awt.Color(51, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Adult");
        flightTicket.add(jLabel8);
        jLabel8.setBounds(40, 170, 116, 23);
        flightTicket.add(jSpinner1);
        jSpinner1.setBounds(280, 206, 210, 30);
        flightTicket.add(jSpinner2);
        jSpinner2.setBounds(40, 206, 200, 30);

        seatClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seatClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "Business", "First" }));
        seatClass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatClass.setLabeText("");
        seatClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatClassActionPerformed(evt);
            }
        });
        flightTicket.add(seatClass);
        seatClass.setBounds(510, 120, 208, 34);

        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        from.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from.setLabeText("");
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        flightTicket.add(from);
        from.setBounds(40, 50, 200, 34);

        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)" }));
        to.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        to.setLabeText("");
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        flightTicket.add(to);
        to.setBounds(270, 50, 200, 34);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(45, 45));
        flightTicket.add(jLabel18);
        jLabel18.setBounds(530, 200, 40, 40);

        button6.setBackground(new java.awt.Color(0, 153, 255));
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setText("SEARCH FLIGHTS");
        button6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        flightTicket.add(button6);
        button6.setBounds(520, 200, 190, 39);

        hotelTicket.setBackground(new java.awt.Color(255, 255, 255));
        hotelTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        hotelTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        hotelTicket.setLayout(null);

        departure2.setBackground(new java.awt.Color(255, 255, 255));
        departure2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTicket.add(departure2);
        departure2.setBounds(270, 160, 180, 33);

        jLabel25.setBackground(new java.awt.Color(51, 204, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Check Out");
        hotelTicket.add(jLabel25);
        jLabel25.setBounds(270, 130, 116, 23);

        from2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)", "Bangka (PGK)", "Lombok (LOP)" }));
        from2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from2.setLabeText("");
        from2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from2ActionPerformed(evt);
            }
        });
        hotelTicket.add(from2);
        from2.setBounds(30, 80, 590, 34);

        jLabel31.setBackground(new java.awt.Color(51, 204, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Destination or City");
        hotelTicket.add(jLabel31);
        jLabel31.setBounds(30, 50, 116, 23);

        jLabel32.setBackground(new java.awt.Color(51, 204, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Hotel Details");
        hotelTicket.add(jLabel32);
        jLabel32.setBounds(30, 20, 116, 23);

        departure4.setBackground(new java.awt.Color(255, 255, 255));
        departure4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hotelTicket.add(departure4);
        departure4.setBounds(30, 160, 200, 33);

        jLabel36.setBackground(new java.awt.Color(51, 204, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Check In");
        hotelTicket.add(jLabel36);
        jLabel36.setBounds(30, 130, 116, 23);

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Guests");
        hotelTicket.add(jLabel37);
        jLabel37.setBounds(470, 130, 40, 23);
        hotelTicket.add(jSpinner7);
        jSpinner7.setBounds(470, 160, 100, 30);

        jLabel38.setBackground(new java.awt.Color(51, 204, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Rooms");
        hotelTicket.add(jLabel38);
        jLabel38.setBounds(590, 130, 40, 23);
        hotelTicket.add(jSpinner8);
        jSpinner8.setBounds(590, 160, 90, 30);

        jLabel28.setBackground(new java.awt.Color(51, 204, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Child");
        hotelTicket.add(jLabel28);
        jLabel28.setBounds(270, 210, 116, 23);

        jLabel30.setBackground(new java.awt.Color(51, 204, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Adult");
        hotelTicket.add(jLabel30);
        jLabel30.setBounds(30, 210, 116, 23);
        hotelTicket.add(jSpinner5);
        jSpinner5.setBounds(270, 230, 210, 30);
        hotelTicket.add(jSpinner6);
        jSpinner6.setBounds(30, 230, 200, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(45, 45));
        hotelTicket.add(jLabel17);
        jLabel17.setBounds(520, 220, 40, 40);

        button5.setBackground(new java.awt.Color(0, 153, 255));
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setText("SEARCH HOTELS");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        hotelTicket.add(button5);
        button5.setBounds(514, 220, 190, 39);

        jLayeredPane2.setLayer(flightTicket, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(hotelTicket, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image-11.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(310, 150));

        jLabel11.setBackground(new java.awt.Color(0, 153, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoFlyStay.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("FlyStay");

        flightButton1.setBackground(new java.awt.Color(0, 153, 255));
        flightButton1.setForeground(new java.awt.Color(255, 255, 255));
        flightButton1.setText("LOG OUT");
        flightButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightButton1ActionPerformed(evt);
            }
        });

        country.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indonesia (ID)", "Indonesia (ENG)" }));
        country.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        country.setLabeText("");
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Country & Languange");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indo.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("My Booking");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/test.png"))); // NOI18N

        javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
        mainPage.setLayout(mainPageLayout);
        mainPageLayout.setHorizontalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(switchOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        mainPageLayout.setVerticalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(switchOnOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addComponent(flightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(mainPage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1550, 1100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void flightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightButtonActionPerformed
        // TODO add your handling code here:
        new hotelFlight().setVisible(true);
    }//GEN-LAST:event_flightButtonActionPerformed

    private void hotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelButtonActionPerformed
        // TODO add your handling code here:
        flightTicket.setVisible(false);
        hotelTicket.setVisible(true);
    }//GEN-LAST:event_hotelButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            returnDate.setVisible(true);    
        }else{
            returnDate.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void seatClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatClassActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void flightButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightButton1ActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void from2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void showForm(Component com) {
        mainPage.removeAll();
        mainPage.add(com);
        mainPage.repaint();
        mainPage.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        FlatLaf.registerCustomDefaultsSource("com.raven.style");
        FlatIntelliJLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button5;
    private swing.Button button6;
    private swing.Combobox country;
    private com.toedter.calendar.JDateChooser departure;
    private com.toedter.calendar.JDateChooser departure2;
    private com.toedter.calendar.JDateChooser departure4;
    private swing.Button flightButton;
    private swing.Button flightButton1;
    private javax.swing.JPanel flightTicket;
    private swing.Combobox from;
    private swing.Combobox from2;
    private swing.Button hotelButton;
    private javax.swing.JPanel hotelTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JPanel mainPage;
    private com.toedter.calendar.JDateChooser returnDate;
    private swing.Combobox seatClass;
    private slideshow.Slideshow slideshow1;
    private switchbutton.SwitchButton switchOnOff;
    private swing.Combobox to;
    // End of variables declaration//GEN-END:variables
}
