/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

//import static Connection.DBpendataan.con;
import Connection.DatabaseConnection;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.Timer;
import java.awt.EventQueue;
import java.text.DecimalFormat;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import switchbutton.SwitchListener;
import static test.FlightBuy.FlightPrice;
import static test.FlightBuy.FlightPrice2;

/**
 *
 * @author Ridho Syahfero
 */
public class PaymentFrame extends javax.swing.JFrame {
    Timer timer;
    int sec, min;
    int i = 0, u = 0;
    boolean cek1 = false;
    boolean cek2 = false;
    boolean cek3 = false;
    boolean cek4 = false;
    private final Connection con;

    /**
     * Creates new form PaymentFrame
     */
    public PaymentFrame() {
        initComponents();
        con = DatabaseConnection.getInstance().getCon();
        dest1.setText(hotelFlight2.departuree.getDate().toString().substring(0,10));
        dest2.setText("- " + hotelFlight2.fromm.getSelectedItem().toString() + " / " + hotelFlight2.too.getSelectedItem().toString());
        indoalfaPanel.setVisible(false);
        jLabel4.setForeground(Color.BLACK);
        jPanel5.setBackground(Color.WHITE);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton5.setVisible(false);    
        jButton11.setVisible(false);    
        jScrollPane1.setHorizontalScrollBarPolicy(jScrollPane1.HORIZONTAL_SCROLLBAR_NEVER);
//       System.out.println(biayaLang.getText());
        Random r = new Random( System.currentTimeMillis() );
        int nilai = ((1 + r.nextInt(2)) * 10000000 + r.nextInt(10000000));
        jLabel3.setText("10" + nilai);
        kodeUnik.setText("Rp " + String.valueOf(nilai).substring(String.valueOf(nilai).length()-3));
        kodeUnik1.setText("Rp " + String.valueOf(nilai).substring(String.valueOf(nilai).length()-3));
        switchOnOff.addEventSwitchSelected(new SwitchListener() {
            @Override
            public void selectChange(boolean on) {
               if(on == true){
                    EventQueue.invokeLater(() -> {
                    jTextField1.setVisible(true);
                    jButton5.setVisible(true);
                    });
               }else{
                    EventQueue.invokeLater(() -> {
                    jTextField1.setVisible(false);
                    jButton5.setVisible(false);
                    });
               }
            }
        });
        switchOnOff1.addEventSwitchSelected(new SwitchListener() {
            @Override
            public void selectChange(boolean on) {
               if(on == true){
                    EventQueue.invokeLater(() -> {
                    jTextField2.setVisible(true);
                    jButton11.setVisible(true);
                    });
               }else{
                    EventQueue.invokeLater(() -> {
                    jTextField2.setVisible(false);
                    jButton11.setVisible(false);
                    });
               }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        atmPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        namaPayment = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        switchOnOff = new switchbutton.SwitchButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kodeUnik = new javax.swing.JLabel();
        namapes1 = new javax.swing.JLabel();
        hargaBayar = new javax.swing.JLabel();
        namapes2 = new javax.swing.JLabel();
        Asuransi = new javax.swing.JLabel();
        namapes3 = new javax.swing.JLabel();
        kuponPromo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        namapes4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        namapes5 = new javax.swing.JLabel();
        biayaLang = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        indoalfaPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        switchOnOff1 = new switchbutton.SwitchButton();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        kodeUnik1 = new javax.swing.JLabel();
        namapes8 = new javax.swing.JLabel();
        hargaBayar1 = new javax.swing.JLabel();
        namapes9 = new javax.swing.JLabel();
        Asuransi1 = new javax.swing.JLabel();
        namapes10 = new javax.swing.JLabel();
        kuponPromo1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        namapes11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        namapes12 = new javax.swing.JLabel();
        biayaLang1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        namaPayment2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        namaT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        namaT2 = new javax.swing.JLabel();
        dest1 = new javax.swing.JLabel();
        dest2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        dest3 = new javax.swing.JLabel();
        dest4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        iconG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FlyStay Pay");

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bank Transfer");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alfamart");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Indomaret");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_home_30px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RETURN TO MAIN PAGE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))))
        );

        atmPanel.setBackground(new java.awt.Color(255, 255, 255));
        atmPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mandiri logos.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        atmPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, -1));

        namaPayment.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaPayment.setText("Bank Transfer");
        atmPanel.add(namaPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_info_24px_1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Anda bisa transfer dari layanan perbank apapun");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("(m-banking, SMS banking atau ATM).");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        atmPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 131, -1, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bni logo.jpg"))); // NOI18N
        atmPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bri images.jpg"))); // NOI18N
        atmPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel11.setText("Tambahkan Kupon");
        atmPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bca logos.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        atmPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 281, 80, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton1.setText("  Transfer MANDIRI");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 410, 64));

        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton2.setText("  Transfer BRI");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 410, 64));

        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton3.setText("  Transfer BNI");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 410, 64));

        jButton4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton4.setText("  Transfer BCA");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 410, 64));

        switchOnOff.setForeground(new java.awt.Color(0, 0, 0));
        switchOnOff.setOn(false);
        switchOnOff.setRound(999);
        switchOnOff.setSwitchColor(new java.awt.Color(102, 204, 255));
        atmPanel.add(switchOnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel15.setText("Pilih Rekening Tujuan");
        atmPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 241, -1, -1));
        atmPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 260, 40));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton5.setText("GUNAKAN KUPON");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 140, 40));

        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCheckBox1.setText("Asuransi Perjalanan");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        atmPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Rp 88.500");
        atmPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel18.setText("Rincian Harga");
        atmPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        kodeUnik.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kodeUnik.setText("Jlabel19");
        atmPanel.add(kodeUnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 870, 90, -1));

        namapes1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes1.setText("jlabel6");
        atmPanel.add(namapes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 210, -1));

        hargaBayar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        hargaBayar.setText("jLabel19");
        atmPanel.add(hargaBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 750, 110, -1));

        namapes2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes2.setText("Asuransi Perjalan");
        atmPanel.add(namapes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, -1, -1));

        Asuransi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Asuransi.setText("Rp 0.00");
        atmPanel.add(Asuransi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 780, 90, -1));

        namapes3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes3.setText("Kupon Promo");
        atmPanel.add(namapes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, -1, -1));

        kuponPromo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        atmPanel.add(kuponPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 810, 110, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_info_24px_2.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        atmPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 840, -1, 20));

        namapes4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes4.setText("Biaya Langganan");
        atmPanel.add(namapes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 840, -1, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        atmPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 900, 410, 10));

        namapes5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes5.setText("Kode Unik");
        atmPanel.add(namapes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 870, -1, -1));

        biayaLang.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        biayaLang.setText("Rp 14.000");
        atmPanel.add(biayaLang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 840, 90, -1));

        jButton6.setBackground(new java.awt.Color(255, 102, 0));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Pay with Bank QRIS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        atmPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 920, 170, 40));

        indoalfaPanel.setBackground(new java.awt.Color(255, 255, 255));
        indoalfaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel35.setText("Tambahkan Kupon");
        indoalfaPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        switchOnOff1.setForeground(new java.awt.Color(0, 0, 0));
        switchOnOff1.setOn(false);
        switchOnOff1.setRound(999);
        switchOnOff1.setSwitchColor(new java.awt.Color(102, 204, 255));
        indoalfaPanel.add(switchOnOff1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        indoalfaPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 40));

        jButton11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton11.setText("GUNAKAN KUPON");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        indoalfaPanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 140, 40));

        jCheckBox2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCheckBox2.setText("Asuransi Perjalanan");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        indoalfaPanel.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel38.setText("Rp 88.500");
        indoalfaPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel39.setText("Rincian Harga");
        indoalfaPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        kodeUnik1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kodeUnik1.setText("Jlabel19");
        indoalfaPanel.add(kodeUnik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, 90, -1));

        namapes8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes8.setText("jlabel6");
        indoalfaPanel.add(namapes8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        hargaBayar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        hargaBayar1.setText("jLabel19");
        indoalfaPanel.add(hargaBayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 110, -1));

        namapes9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes9.setText("Asuransi Perjalan");
        indoalfaPanel.add(namapes9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        Asuransi1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Asuransi1.setText("Rp 0.00");
        indoalfaPanel.add(Asuransi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 90, -1));

        namapes10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes10.setText("Kupon Promo");
        indoalfaPanel.add(namapes10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        kuponPromo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        indoalfaPanel.add(kuponPromo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 120, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_info_24px_2.png"))); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        indoalfaPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, -1, 20));

        namapes11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes11.setText("Biaya Langganan");
        indoalfaPanel.add(namapes11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, -1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        indoalfaPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 410, 10));

        namapes12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namapes12.setText("Kode Unik");
        indoalfaPanel.add(namapes12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        biayaLang1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        biayaLang1.setText("Rp 14.000");
        indoalfaPanel.add(biayaLang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 90, -1));

        jButton12.setBackground(new java.awt.Color(255, 102, 0));
        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Pay with Indomaret");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        indoalfaPanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, 170, 40));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indomarett.png"))); // NOI18N
        jLabel27.setText("INDOMARET");
        indoalfaPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 110, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setText("Baca Sebelum Membayar");
        indoalfaPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        namaPayment2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaPayment2.setText("Indomaret");
        indoalfaPanel.add(namaPayment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel32.setText("- Biaya tersebut dapat berubah sewaktu - waktu ");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel33.setText("tanpa pemberitahuan");

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel34.setText("- Terdapat biaya tambahan dari Indomaret");

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel37.setText("Rp 5000 / Transaksi");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        indoalfaPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 410, 150));

        jLayeredPane1.setLayer(atmPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(indoalfaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(atmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(indoalfaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(indoalfaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 41, -1, 1070));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        namaT.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        namaT.setForeground(new java.awt.Color(102, 102, 102));
        namaT.setText("Perjalanan Anda");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 153));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("No Pesanan");

        namaT2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namaT2.setText("Penerbangan");

        dest1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dest1.setForeground(new java.awt.Color(102, 102, 102));
        dest1.setText("jLabel3");

        dest2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dest2.setForeground(new java.awt.Color(102, 102, 102));
        dest2.setText("jLabel3");

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel44.setText("Penumpang");

        dest3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dest3.setForeground(new java.awt.Color(102, 102, 102));
        dest3.setText("jLabel3");

        dest4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dest4.setForeground(new java.awt.Color(102, 102, 102));
        dest4.setText("jLabel3");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N

        iconG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_airplane_take_off_26px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dest3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dest4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addComponent(namaT2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dest1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(namaT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconG)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaT)
                    .addComponent(iconG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dest1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dest2)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dest3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dest4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 240, 310));

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            Asuransi.setText("Rp 88.500");
            String query = "UPDATE pesanan set asuransi_perjalanan=? WHERE no_pesanan=?";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, Asuransi.getText().substring(3));
                    DatabaseConnection.pst.setString(2, jLabel3.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            Asuransi.setText("Rp 0.00");            
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setBorder(new LineBorder(Color.BLUE));
        jButton1.setBorder(new LineBorder(Color.BLACK));
        jButton2.setBorder(new LineBorder(Color.BLACK));
        jButton3.setBorder(new LineBorder(Color.BLACK));
        cek3 = true;
        cek4 = false;
        cek1 = true;
        cek2 = false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setBorder(new LineBorder(Color.BLUE));
        jButton1.setBorder(new LineBorder(Color.BLACK));
        jButton2.setBorder(new LineBorder(Color.BLACK));
        jButton4.setBorder(new LineBorder(Color.BLACK));
        cek3 = false;
        cek4 = true;
        cek1 = false;
        cek2 = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setBorder(new LineBorder(Color.BLUE));
        jButton1.setBorder(new LineBorder(Color.BLACK));
        jButton4.setBorder(new LineBorder(Color.BLACK));
        jButton3.setBorder(new LineBorder(Color.BLACK));
        cek3 = true;
        cek4 = false;
        cek1 = false;
        cek2 = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBorder(new LineBorder(Color.BLUE));
        jButton2.setBorder(new LineBorder(Color.BLACK));
        jButton3.setBorder(new LineBorder(Color.BLACK));
        jButton4.setBorder(new LineBorder(Color.BLACK));
        cek3 = false;
        cek4 = false;
        cek1 = false;
        cek2 = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        jLabel6.setForeground(Color.BLACK);
        jPanel7.setBackground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
        jPanel5.setBackground(new Color(0,51,102));
        jLabel5.setForeground(Color.WHITE);
        jPanel6.setBackground(new Color(0,51,102));
        atmPanel.setVisible(false);
        indoalfaPanel.setVisible(true);
        namaPayment2.setText("Indomaret");
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indomarett.png")));
        jLabel34.setText("- Terdapat biaya tambahan dari Indomaret");
        jButton12.setText("Pay with Indomaret");
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jLabel6.setForeground(Color.BLACK);
        jPanel7.setBackground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
        jPanel5.setBackground(new Color(0,51,102));
        jLabel5.setForeground(Color.WHITE);
        jPanel6.setBackground(new Color(0,51,102));
        atmPanel.setVisible(false);
        indoalfaPanel.setVisible(true);
        namaPayment2.setText("Indomaret");
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indomarett.png")));
        jLabel34.setText("- Terdapat biaya tambahan dari Indomaret");
        jButton12.setText("Pay with Indomaret");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        jLabel5.setForeground(Color.BLACK);
        jPanel6.setBackground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
        jPanel5.setBackground(new Color(0,51,102));
        jLabel6.setForeground(Color.WHITE);
        jPanel7.setBackground(new Color(0,51,102));
        atmPanel.setVisible(false);
        namaPayment2.setText("Alfamart");
        indoalfaPanel.setVisible(true);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alfamart.png")));
        jLabel34.setText("- Terdapat biaya tambahan dari Alfamart");
        jButton12.setText("Pay with Alfamart");
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jLabel5.setForeground(Color.BLACK);
        jPanel6.setBackground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
        jPanel5.setBackground(new Color(0,51,102));
        jLabel6.setForeground(Color.WHITE);
        jPanel7.setBackground(new Color(0,51,102));
        atmPanel.setVisible(false);
        indoalfaPanel.setVisible(true);
        namaPayment2.setText("Alfamart");
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alfamart.png")));
        jLabel34.setText("- Terdapat biaya tambahan dari Alfamart");
        jButton12.setText("Pay with Alfamart");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        jLabel4.setForeground(Color.BLACK);
        jPanel5.setBackground(Color.WHITE);
        jLabel5.setForeground(Color.WHITE);
        jPanel6.setBackground(new Color(0,51,102));
        jLabel6.setForeground(Color.WHITE);
        jPanel7.setBackground(new Color(0,51,102));
        atmPanel.setVisible(true);
        indoalfaPanel.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jLabel4.setForeground(Color.BLACK);
        jPanel5.setBackground(Color.WHITE);
        jLabel5.setForeground(Color.WHITE);
        jPanel6.setBackground(new Color(0,51,102));
        jLabel6.setForeground(Color.WHITE);
        jPanel7.setBackground(new Color(0,51,102));
        atmPanel.setVisible(true);
        indoalfaPanel.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField1.getText().equals("LEBIHHEMAT50")){
            if(i == 0){
            JOptionPane.showMessageDialog(null, "Kupon Valid, Selamat Anda Mendaptkan Potongan Harga 50Rb Hanya Untuk Tiket Pesawat");
            kuponPromo.setText("LEBIHHEMAT50");
            String query = "UPDATE pesanan set kupon_promo=? WHERE no_pesanan=?";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, kuponPromo.getText());
                    DatabaseConnection.pst.setString(2, jLabel3.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
            }else{
                JOptionPane.showMessageDialog(null, "Kode sudah anda gunakan");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Maaf Kode Yang Anda Masukan Invalid");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        JOptionPane.showConfirmDialog(null, "Untuk terus memberikan kualitas layanan terbaik yang mendukung kebutuhan perjalanan dan lifestyle anda.", "Biaya Langganan",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(cek1 == true || cek2 == true || cek3 == true || cek4 == true){
            QRISBCA qris = new QRISBCA(this, true);
            qris.setVisible(true);
            String query = "INSERT INTO pesanan (no_pesanan,harga_pesanan,biaya_langganan,kode_unik,jenis_pembayaran) VALUES(?,?,?,?,?)";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, jLabel3.getText());
                    DatabaseConnection.pst.setString(2, QRISBCA.jLabel5.getText().substring(3));
                    DatabaseConnection.pst.setString(3, biayaLang.getText().substring(3));
                    DatabaseConnection.pst.setString(4, kodeUnik.getText().substring(3));
                    DatabaseConnection.pst.setString(5, namaPayment.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Harap Mengisi Rekening Tujuan");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    if(jTextField2.getText().equals("LEBIHHEMAT50")){
        if(u == 0){    
            JOptionPane.showMessageDialog(null, "Kupon Valid, Selamat Anda Mendaptkan Potongan Harga 50Rb Hanya Untuk Tiket Pesawat");
            kuponPromo1.setText("LEBIHHEMAT50");
            String query = "UPDATE pesanan set kupon_promo=? WHERE no_pesanan=?";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, kuponPromo1.getText());
                    DatabaseConnection.pst.setString(2, jLabel3.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            u++;
        }else{
            JOptionPane.showMessageDialog(null, "Kode sudah anda gunakan");
        }  
    }else{
        JOptionPane.showMessageDialog(null, "Maaf Kode Yang Anda Masukan Invalid");
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()){
            Asuransi1.setText("Rp 88.500");
            String query = "UPDATE pesanan set asuransi_perjalanan=? WHERE no_pesanan=?";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, Asuransi1.getText().substring(3));
                    DatabaseConnection.pst.setString(2, jLabel3.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            Asuransi1.setText("Rp 0.00");            
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        JOptionPane.showConfirmDialog(null, "Untuk terus memberikan kualitas layanan terbaik yang mendukung kebutuhan perjalanan dan lifestyle anda.", "Biaya Langganan",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        GeraiPayment pay = new GeraiPayment(this,true);
        if(namaPayment2.getText().equals("Indomaret")){
            GeraiPayment.namaGerai.setText(namaPayment2.getText());
            GeraiPayment.namaGerai.setText("Petunjuk Pembayaran Indomaret");
            GeraiPayment.gambarGerai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indomarett.png")));
            GeraiPayment.nambaone.setText("1. Beritahu kasir Indomaret jika kamu ingin melakukan");
            GeraiPayment.nambatwo.setText("2. Lihatkan kode pembayaran kamu ke kasir Indomaret");
            String query = "INSERT INTO pesanan (no_pesanan,harga_pesanan,biaya_langganan,kode_unik,jenis_pembayaran) VALUES(?,?,?,?,?)";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, jLabel3.getText());
                    DatabaseConnection.pst.setString(2, GeraiPayment.hargaTotal.getText().substring(3));
                    DatabaseConnection.pst.setString(3, biayaLang1.getText().substring(3));
                    DatabaseConnection.pst.setString(4, kodeUnik1.getText().substring(3));
                    DatabaseConnection.pst.setString(5, namaPayment2.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            pay.setVisible(true);
        }else{
            String query = "INSERT INTO pesanan (no_pesanan,harga_pesanan,biaya_langganan,kode_unik,jenis_pembayaran) VALUES(?,?,?,?,?)";
            try {
                DatabaseConnection.pst = con.prepareStatement(query);
                    DatabaseConnection.pst.setString(1, jLabel3.getText());
                    DatabaseConnection.pst.setString(2, GeraiPayment.hargaTotal.getText().substring(3));
                    DatabaseConnection.pst.setString(3, biayaLang1.getText().substring(3));
                    DatabaseConnection.pst.setString(4, kodeUnik1.getText().substring(3));
                    DatabaseConnection.pst.setString(5, namaPayment2.getText());
                    DatabaseConnection.pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            pay.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
        Main tes = new Main();
        tes.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        Main tes = new Main();
        tes.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatIntelliJLaf.setup();
        try {
            DatabaseConnection.getInstance().connectToDatabase();
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Asuransi;
    public static javax.swing.JLabel Asuransi1;
    private javax.swing.JPanel atmPanel;
    public static javax.swing.JLabel biayaLang;
    public static javax.swing.JLabel biayaLang1;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JLabel dest1;
    public static javax.swing.JLabel dest2;
    public static javax.swing.JLabel dest3;
    public static javax.swing.JLabel dest4;
    public static javax.swing.JLabel hargaBayar;
    public static javax.swing.JLabel hargaBayar1;
    public static javax.swing.JLabel iconG;
    private javax.swing.JPanel indoalfaPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel kodeUnik;
    public static javax.swing.JLabel kodeUnik1;
    public static javax.swing.JLabel kuponPromo;
    public static javax.swing.JLabel kuponPromo1;
    public static javax.swing.JLabel namaPayment;
    public static javax.swing.JLabel namaPayment2;
    public javax.swing.JLabel namaT;
    public static javax.swing.JLabel namaT2;
    public static javax.swing.JLabel namapes1;
    public static javax.swing.JLabel namapes10;
    public static javax.swing.JLabel namapes11;
    public static javax.swing.JLabel namapes12;
    public static javax.swing.JLabel namapes2;
    public static javax.swing.JLabel namapes3;
    public static javax.swing.JLabel namapes4;
    public static javax.swing.JLabel namapes5;
    public static javax.swing.JLabel namapes8;
    public static javax.swing.JLabel namapes9;
    private switchbutton.SwitchButton switchOnOff;
    private switchbutton.SwitchButton switchOnOff1;
    // End of variables declaration//GEN-END:variables
}
