/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.awt.Color;
import java.awt.EventQueue;
import switchbutton.SwitchListener;
import test.hotelFlight;

/**
 *
 * @author DELL
 */
public class transportation extends javax.swing.JFrame {

    /**
     * Creates new form transportation
     */
    public transportation() {
        initComponents();
        slideshow1.initSlideshow(new Slide5(), new Slide6(), new Slide7());
//           switchOnOff.addEventSwitchSelected(new SwitchListener() {
//            @Override
//            public void selectChange(boolean on) {
//               if(on == true){
//                    EventQueue.invokeLater(() -> {
//                    FlatAnimatedLafChange.showSnapshot();
//                    FlatDarculaLaf.setup();
//                    FlatLaf.updateUI();
//                    FlatAnimatedLafChange.hideSnapshotWithAnimation();
//                    mainPage.setBackground(Color.DARK_GRAY);
//                    switchOnOff.setSwitchColor(new Color(102,204,255));
//                    switchOnOff.setForeground(Color.BLACK);
//                    });
//               }else{
//                    EventQueue.invokeLater(() -> {
//                    FlatAnimatedLafChange.showSnapshot();
//                    FlatIntelliJLaf.setup();
//                    FlatLaf.updateUI();
//                    FlatAnimatedLafChange.hideSnapshotWithAnimation();
//                    mainPage.setBackground(Color.WHITE);
//                    switchOnOff.setSwitchColor(new Color(102,204,255));
//                    switchOnOff.setForeground(Color.BLACK);   
//                    });
//               }
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPage = new javax.swing.JPanel();
        switchOnOff = new switchbutton.SwitchButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slideshow1 = new slideshow.Slideshow();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        flightButton1 = new swing.Button();
        country = new swing.Combobox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        materialTabbed1 = new swing.MaterialTabbed();
        flightTicket = new javax.swing.JPanel();
        departure = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        returnDate = new com.toedter.calendar.JDateChooser();
        button4 = new swing.Button();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        seatClass = new swing.Combobox();
        from = new swing.Combobox();
        to = new swing.Combobox();
        flightTicket2 = new javax.swing.JPanel();
        departure2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        returnDate2 = new com.toedter.calendar.JDateChooser();
        button6 = new swing.Button();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        seatClass2 = new swing.Combobox();
        from2 = new swing.Combobox();
        to2 = new swing.Combobox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        from3 = new swing.Combobox();
        from4 = new swing.Combobox();
        jLabel34 = new javax.swing.JLabel();
        departure3 = new com.toedter.calendar.JDateChooser();
        departure4 = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1600, 1100));

        mainPage.setBackground(new java.awt.Color(255, 255, 255));
        mainPage.setPreferredSize(new java.awt.Dimension(1550, 915));

        switchOnOff.setForeground(new java.awt.Color(0, 0, 0));
        switchOnOff.setOn(false);
        switchOnOff.setRound(999);
        switchOnOff.setSwitchColor(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Dark Mode");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image17.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(310, 150));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        slideshow1.setForeground(new java.awt.Color(102, 255, 255));
        slideshow1.setPreferredSize(new java.awt.Dimension(478, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image15.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image16.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(310, 150));

        jLabel11.setBackground(new java.awt.Color(0, 153, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoFlyStay.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("FlyStay");

        flightButton1.setBackground(new java.awt.Color(0, 153, 255));
        flightButton1.setForeground(new java.awt.Color(255, 255, 255));
        flightButton1.setText("LOG OUT");
        flightButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightButton1ActionPerformed(evt);
            }
        });

        country.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indonesia (ID)", "Indonesia (ENG)" }));
        country.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        country.setLabeText("");
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Country & Languange");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/indo.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("My Booking");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/test.png"))); // NOI18N

        materialTabbed1.setForeground(new java.awt.Color(0, 0, 0));
        materialTabbed1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        materialTabbed1.setPreferredSize(new java.awt.Dimension(735, 287));
        materialTabbed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialTabbed1MouseClicked(evt);
            }
        });

        flightTicket.setBackground(new java.awt.Color(255, 255, 255));
        flightTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        flightTicket.setPreferredSize(new java.awt.Dimension(800, 400));
        flightTicket.setLayout(null);

        departure.setBackground(new java.awt.Color(255, 255, 255));
        departure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(departure);
        departure.setBounds(41, 120, 200, 33);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Departure Date");
        flightTicket.add(jLabel3);
        jLabel3.setBounds(41, 91, 116, 23);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Return Date");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        flightTicket.add(jRadioButton1);
        jRadioButton1.setBounds(275, 92, 100, 21);

        returnDate.setBackground(new java.awt.Color(255, 255, 255));
        returnDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket.add(returnDate);
        returnDate.setBounds(276, 120, 210, 33);

        button4.setBackground(new java.awt.Color(0, 153, 255));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("SEARCH FLIGHTS");
        button4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        flightTicket.add(button4);
        button4.setBounds(520, 200, 164, 39);

        jLabel4.setBackground(new java.awt.Color(51, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seat Class");
        flightTicket.add(jLabel4);
        jLabel4.setBounds(510, 90, 116, 23);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("To");
        flightTicket.add(jLabel5);
        jLabel5.setBounds(275, 20, 116, 23);

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Child");
        flightTicket.add(jLabel6);
        jLabel6.setBounds(280, 170, 116, 23);

        jLabel7.setBackground(new java.awt.Color(51, 204, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("From");
        flightTicket.add(jLabel7);
        jLabel7.setBounds(41, 20, 116, 23);

        jLabel8.setBackground(new java.awt.Color(51, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Adult");
        flightTicket.add(jLabel8);
        jLabel8.setBounds(40, 170, 116, 23);
        flightTicket.add(jSpinner1);
        jSpinner1.setBounds(280, 206, 210, 30);
        flightTicket.add(jSpinner2);
        jSpinner2.setBounds(40, 206, 200, 30);

        seatClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seatClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "Business", "First" }));
        seatClass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatClass.setLabeText("");
        seatClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatClassActionPerformed(evt);
            }
        });
        flightTicket.add(seatClass);
        seatClass.setBounds(510, 120, 208, 34);

        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        from.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from.setLabeText("");
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        flightTicket.add(from);
        from.setBounds(40, 50, 200, 34);

        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)" }));
        to.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        to.setLabeText("");
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        flightTicket.add(to);
        to.setBounds(270, 50, 200, 34);

        materialTabbed1.addTab("FLIGHTS", flightTicket);

        flightTicket2.setBackground(new java.awt.Color(255, 255, 255));
        flightTicket2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        flightTicket2.setPreferredSize(new java.awt.Dimension(800, 400));
        flightTicket2.setLayout(null);

        departure2.setBackground(new java.awt.Color(255, 255, 255));
        departure2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket2.add(departure2);
        departure2.setBounds(420, 340, 140, 33);

        jLabel25.setBackground(new java.awt.Color(51, 204, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Check Out");
        flightTicket2.add(jLabel25);
        jLabel25.setBounds(420, 310, 116, 23);

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setText("Return Date");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        flightTicket2.add(jRadioButton3);
        jRadioButton3.setBounds(280, 130, 100, 21);

        returnDate2.setBackground(new java.awt.Color(255, 255, 255));
        returnDate2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket2.add(returnDate2);
        returnDate2.setBounds(280, 150, 210, 33);

        button6.setBackground(new java.awt.Color(0, 153, 255));
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setText("SEARCH FLIGHTS");
        button6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        flightTicket2.add(button6);
        button6.setBounds(520, 220, 164, 39);

        jLabel26.setBackground(new java.awt.Color(51, 204, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Seat Class");
        flightTicket2.add(jLabel26);
        jLabel26.setBounds(510, 120, 116, 23);

        jLabel27.setBackground(new java.awt.Color(51, 204, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("To");
        flightTicket2.add(jLabel27);
        jLabel27.setBounds(280, 50, 116, 23);

        jLabel28.setBackground(new java.awt.Color(51, 204, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Child");
        flightTicket2.add(jLabel28);
        jLabel28.setBounds(280, 200, 116, 23);

        jLabel29.setBackground(new java.awt.Color(51, 204, 255));
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("------------------------------------------------------------------------------------------------------------------------------------------------");
        flightTicket2.add(jLabel29);
        jLabel29.setBounds(20, 260, 700, 23);

        jLabel30.setBackground(new java.awt.Color(51, 204, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Adult");
        flightTicket2.add(jLabel30);
        jLabel30.setBounds(40, 200, 116, 23);
        flightTicket2.add(jSpinner5);
        jSpinner5.setBounds(280, 220, 210, 30);
        flightTicket2.add(jSpinner6);
        jSpinner6.setBounds(40, 220, 200, 30);

        seatClass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seatClass2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "Business", "First" }));
        seatClass2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatClass2.setLabeText("");
        seatClass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatClass2ActionPerformed(evt);
            }
        });
        flightTicket2.add(seatClass2);
        seatClass2.setBounds(510, 150, 208, 34);

        from2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)", "Bangka (PGK)", "Lombok (LOP)" }));
        from2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from2.setLabeText("");
        from2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from2ActionPerformed(evt);
            }
        });
        flightTicket2.add(from2);
        from2.setBounds(40, 340, 200, 34);

        to2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        to2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangka (PGK)", "Lombok (LOP)", "Bali (DPS)" }));
        to2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        to2.setLabeText("");
        to2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to2ActionPerformed(evt);
            }
        });
        flightTicket2.add(to2);
        to2.setBounds(280, 80, 200, 34);

        jLabel31.setBackground(new java.awt.Color(51, 204, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Destination or City");
        flightTicket2.add(jLabel31);
        jLabel31.setBounds(40, 310, 116, 23);

        jLabel32.setBackground(new java.awt.Color(51, 204, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Hotel Details");
        flightTicket2.add(jLabel32);
        jLabel32.setBounds(40, 280, 116, 23);

        jLabel33.setBackground(new java.awt.Color(51, 204, 255));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Flight Details");
        flightTicket2.add(jLabel33);
        jLabel33.setBounds(40, 20, 116, 23);

        from3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        from3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from3.setLabeText("");
        from3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from3ActionPerformed(evt);
            }
        });
        flightTicket2.add(from3);
        from3.setBounds(40, 80, 200, 34);

        from4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        from4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jakarta (JKT)", "Surabaya (SBY)", "Bali (DPS)" }));
        from4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from4.setLabeText("");
        from4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from4ActionPerformed(evt);
            }
        });
        flightTicket2.add(from4);
        from4.setBounds(40, 80, 200, 34);

        jLabel34.setBackground(new java.awt.Color(51, 204, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("From");
        flightTicket2.add(jLabel34);
        jLabel34.setBounds(40, 50, 116, 23);

        departure3.setBackground(new java.awt.Color(255, 255, 255));
        departure3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket2.add(departure3);
        departure3.setBounds(40, 150, 200, 33);

        departure4.setBackground(new java.awt.Color(255, 255, 255));
        departure4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        flightTicket2.add(departure4);
        departure4.setBounds(270, 340, 140, 33);

        jLabel35.setBackground(new java.awt.Color(51, 204, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Departure Date");
        flightTicket2.add(jLabel35);
        jLabel35.setBounds(40, 130, 116, 23);

        jLabel36.setBackground(new java.awt.Color(51, 204, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Check In");
        flightTicket2.add(jLabel36);
        jLabel36.setBounds(270, 310, 116, 23);

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Guests");
        flightTicket2.add(jLabel37);
        jLabel37.setBounds(570, 310, 40, 23);
        flightTicket2.add(jSpinner7);
        jSpinner7.setBounds(570, 340, 70, 30);

        jLabel38.setBackground(new java.awt.Color(51, 204, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Rooms");
        flightTicket2.add(jLabel38);
        jLabel38.setBounds(650, 310, 40, 23);
        flightTicket2.add(jSpinner8);
        jSpinner8.setBounds(650, 340, 70, 30);

        materialTabbed1.addTab("FLIGHT + HOTEL", flightTicket2);

        javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
        mainPage.setLayout(mainPageLayout);
        mainPageLayout.setHorizontalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123)
                        .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(switchOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        mainPageLayout.setVerticalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(switchOnOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(mainPage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightButton1ActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            returnDate.setVisible(true);
        }else{
            returnDate.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void seatClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatClassActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            returnDate.setVisible(true);
        }else{
            returnDate.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void seatClass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatClass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatClass2ActionPerformed

    private void from2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from2ActionPerformed

    private void to2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to2ActionPerformed

    private void from3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from3ActionPerformed

    private void from4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from4ActionPerformed

    private void materialTabbed1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTabbed1MouseClicked
        // TODO add your handling code here:
        hotelFlight2 setU = new hotelFlight2();
        setU.setVisible(true);
    }//GEN-LAST:event_materialTabbed1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transportation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button4;
    private swing.Button button6;
    private swing.Combobox country;
    private com.toedter.calendar.JDateChooser departure;
    private com.toedter.calendar.JDateChooser departure2;
    private com.toedter.calendar.JDateChooser departure3;
    private com.toedter.calendar.JDateChooser departure4;
    private swing.Button flightButton1;
    private javax.swing.JPanel flightTicket;
    private javax.swing.JPanel flightTicket2;
    private swing.Combobox from;
    private swing.Combobox from2;
    private swing.Combobox from3;
    private swing.Combobox from4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    public static javax.swing.JPanel mainPage;
    private swing.MaterialTabbed materialTabbed1;
    private com.toedter.calendar.JDateChooser returnDate;
    private com.toedter.calendar.JDateChooser returnDate2;
    private swing.Combobox seatClass;
    private swing.Combobox seatClass2;
    private slideshow.Slideshow slideshow1;
    private switchbutton.SwitchButton switchOnOff;
    private swing.Combobox to;
    private swing.Combobox to2;
    // End of variables declaration//GEN-END:variables
}
